### ISSUE TITLE
使用norm 插入点操作报错

### ISSUE THREAD

**Issue by weiGaoCheng** [zhihu/norm#10]
报错   Invalid data length
下面是debug的结果
*(*"github.com/zhihu/norm.VModel")(3203334144) =function calls not supported by this version of Go
麻烦问下norm使用的go版本

**Comment by weiGaoCheng** [comment]
离谱的是我把我的业务代码放在您这边的代码里   用您的*norm.DB执行通过了     我服务里连接数据库的用法和您这边也一模一样的

**Comment by everywan** [comment]
版本在 go.mod 里是有的呢, 1.15. 有具体一些的报错信息么?
