### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by qiaoxincheng0624** [zhihu/norm#13]
[norm](https://github.com/zhihu/norm)/[internal](https://github.com/zhihu/norm/tree/master/internal)/[converts](https://github.com/zhihu/norm/tree/master/internal/converts)/util.go

这个文件import少了一个time，导致setFieldValue方法的time.Unix(ts, 0)这部分编译报错

**Comment by everywan** [comment]
Has Merged. New version: v0.1.11

PS: 上次合并后忘记测试了...

Thanks for your pr~
