### ISSUE TITLE
Bug listed in the dialector.adoc has been fixed

### ISSUE THREAD

**Issue by Aiee** [zhihu/norm#3]
As I tested with both nightly versions of Nebula Graph and console, the bug stated in [here](https://github.com/zhihu/norm/blob/master/docs/dialector.adoc#others) has been fixed in https://github.com/vesoft-inc/nebula-graph/pull/1165.

Also, `nebula.pool.IdleTime` has been used to clean idle connections, as you can find the usage in the [tests](https://github.com/vesoft-inc/nebula-go/blob/5ab4bdcd57db2db17aa3ac0fd8d1f866c578db20/client_test.go#L819-L863)

**Comment by everywan** [comment]
Get it! The reason is i forget update nebula-go version (now use tag(v2.0.0-ga) ). I will update it soon.

Thanks!

**Comment by everywan** [comment]
> IdleTime

We need nebula-go build a new tag!

**Comment by Aiee** [comment]
> > IdleTime
> 
> We need nebula-go build a new tag!

A new tag will be released with the next Nebula release, please use the master branch for now if there are features you need.

**Comment by everywan** [comment]
> > > IdleTime
> > 
> > 
> > We need nebula-go build a new tag!
> 
> A new tag will be released with the next Nebula release, please use the master branch for now if there are features you need.

For now i'm prefer use tag than branch. Because we don't want import unknown change except we really know what we are doing. Use branch maybe import unknown change.
