### ISSUE TITLE
怎么获取数据

### ISSUE THREAD

**Issue by yuu2lee4** [zhihu/norm#8]
nebula官方的客户端获取数据非常麻烦，我看norm特性里有一条Parse Nebula execute result to struct / map，这个有具体的示例么，在样例里没有这块儿的具体体现

**Comment by yuu2lee4** [comment]
大概知道了

**Comment by everywan** [comment]
具体可以参考例子 or gorm 的用法, 很类似.

**Comment by yuu2lee4** [comment]
@everywan   恩 是的 开始没找到，想问一下 我看你们有一些规划  现在有没有日程呢

**Comment by everywan** [comment]
因为工作安排的原因, 之前立的 flag 现在还没完成 🤦‍♂️🤦‍♂️
不过有啥想法和需求欢迎提 issue 或者 pr 哈, 优先搞.

**Comment by hardtome** [comment]
麻烦问下，批量插入点和边有排上日程吗，大概完成的时间是多少喃

**Comment by everywan** [comment]
在开发时已经预留了批量插入的空位, 开发难度不大. 忙完手头上的搞下, 预计下周二之前.

大概方案就是
1. [解析 struct](https://github.com/zhihu/norm/blob/master/internal/converts/insert_vertex.go#L66) 替换为返回 keys, values
2. [生成 gql](https://github.com/zhihu/norm/blob/master/internal/converts/insert_edge.go#L32) 增加对 `[]interface{}` 的判断, 然后处理即可.

着急的话可以提 pr, 拿这个练练手 😎😎
